### ISSUE TITLE
OSX version crash

### ISSUE THREAD

**Issue by rvwoens** [xun-project/UltraNoteWallet#1]
Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/qt/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport
  Referenced from: /Applications/wallets/ultranotewallet.app/Contents/MacOS/ultranotewallet
  Reason: Incompatible library version: ultranotewallet requires version 5.10.0 or later, but QtPrintSupport provides version 5.3.0

**Comment by UltraNote** [comment]
This issue been resolved in wallet version 1.0.4-beta for MAC. Please let us know if you face more problems or if you need more help.
