### ISSUE TITLE
Secure file attachements for messages

### ISSUE THREAD

**Issue by echa** [xun-project/UltraNoteWallet#2]
As an extension to the existing messaging feature we would like to attach documents (images, videos, office documents, etc) to a message. This issue is meant for collecting and discussing ideas on that topic.

### Requirements
* do not store documents on the blockchain (keep reference only)
* optionally encrypt documents before sharing (maybe using the same key as the UltraNote message itself)
* no protocol changes to avoid soft or hard forks

**Comment by UltraNote** [comment]
We have implemented this solution using IPFS:

1. All selected files packed into one archive attachment.
2. Application encrypts attachment with random one-time encryption key and ChaCha algorithm.
3. Attachment archive uploads to IPFS gateway and we get the hash.
4. Hash and encryption key are added as "Attachment" and "Attachment-Encryption-Key" respectively.
5. On receive, when user clicks "Download attachment" button, it downloads and decrypts.
