### ISSUE TITLE
UltraNoteWallet/src/qzip.cpp:504:21: error: ‘class QStringRef’ has no member named ‘chop’

### ISSUE THREAD

**Issue by rlkanter** [xun-project/UltraNoteWallet#6]
I've tried install this on ubuntu and am receiving the following error:

[ 73%] Building CXX object CMakeFiles/UltraNoteWallet.dir/src/qzip.cpp.o
/home/ubuntu/UltraNoteWallet/src/qzip.cpp: In member function ‘QZipReader::FileInfo QZipPrivate::fillFileInfo(int) const’:
/home/ubuntu/UltraNoteWallet/src/qzip.cpp:504:21: error: ‘class QStringRef’ has no member named ‘chop’
         filePathRef.chop(1);
                     ^
CMakeFiles/UltraNoteWallet.dir/build.make:817: recipe for target 'CMakeFiles/UltraNoteWallet.dir/src/qzip.cpp.o' failed

Am I missing something?  Thanks

**Comment by spfoo** [comment]
It's due to the version of Qt. chop was introduced in Qt 5.8. Update your Qt version.
